name: Continuous Integration (MLOps)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Pytest (Unit Testing)
      env:
        PYTHONPATH: .
      run: |
        python -m pytest tests/ -v
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Container Image (API & Model)
      run: |
        echo "Memulai proses build container..."
        # Menjalankan build menggunakan Containerfile Anda dari root direktori
        docker build -f deployment/Containerfile -t titanic-fastapi:latest .
        
    - name: Verifikasi Build Sukses
      run: |
        echo "Container berhasil dirakit! Berikut daftar image di server GitHub:"
        docker images | grep titanic-fastapi